import { MysteryChestPack, MysteryChestItem } from '@/types';

export const CHEST_GRADIENT_COLORS = [
  'from-amber-500 to-orange-500',
  'from-purple-500 to-indigo-500',
  'from-blue-500 to-cyan-500',
  'from-rose-500 to-pink-500',
  'from-emerald-500 to-teal-500',
  'from-yellow-400 to-amber-500',
  'from-violet-500 to-fuchsia-600',
  'from-teal-500 to-green-600',
  'from-sky-500 to-blue-600',
  'from-red-500 to-orange-600',
  'from-lime-500 to-emerald-600',
  'from-indigo-500 to-purple-600',
];

export const DEFAULT_CHEST_PACKS: MysteryChestPack[] = [
  // 1. KHEN THƯỞNG NỀ NẾP & SAO THI ĐUA
  {
    id: 'pack-rewards',
    title: 'Khen Thưởng Nề Nếp & Sao Thi Đua',
    description: 'Phần thưởng tinh thần, sao nề nếp và đặc quyền danh dự dành cho học sinh tích cực.',
    category: 'REWARD',
    icon: '🎁',
    items: [
      {
        id: 'r1',
        type: 'REWARD',
        title: '+2 Sao Thi Đua Nề Nếp',
        badge: '⭐',
        starPoints: 2,
        desc: 'Cộng trực tiếp 2 sao vào Sổ thi đua khen thưởng của em!',
        color: 'from-amber-500 to-orange-500',
      },
      {
        id: 'r2',
        type: 'REWARD',
        title: 'Làm Quản Ca 1 Buổi',
        badge: '👑',
        starPoints: 1,
        desc: 'Được vinh dự lên bục giảng bắt nhịp cho cả lớp hát đầu giờ!',
        color: 'from-purple-500 to-indigo-500',
      },
      {
        id: 'r3',
        type: 'REWARD',
        title: 'Phiếu Miễn Trực Nhật 1 Buổi',
        badge: '🎟️',
        starPoints: 1,
        desc: 'Được miễn nhiệm vụ quét lớp và kê bàn ghế trong 1 buổi trực nhật.',
        color: 'from-blue-500 to-cyan-500',
      },
      {
        id: 'r4',
        type: 'REWARD',
        title: 'Được Chọn Bài Hát Giải Lao',
        badge: '🎵',
        starPoints: 1,
        desc: 'Được quyền yêu cầu cô giáo mở bài hát yêu thích trong giờ nghỉ giải lao!',
        color: 'from-rose-500 to-pink-500',
      },
      {
        id: 'r5',
        type: 'REWARD',
        title: '1 Sticker Khen Thưởng Xinh Xắn',
        badge: '🏷️',
        starPoints: 1,
        desc: 'Nhận ngay 1 hình dán sticker khen thưởng ngộ nghĩnh từ cô giáo!',
        color: 'from-emerald-500 to-teal-500',
      },
      {
        id: 'r6',
        type: 'REWARD',
        title: 'Tràng Pháo Tay Siêu To Khổng Lồ',
        badge: '👏',
        starPoints: 1,
        desc: 'Cả lớp cùng đứng dậy vỗ tay nhiệt liệt chúc mừng em thật rộn ràng!',
        color: 'from-yellow-400 to-amber-500',
      },
      {
        id: 'r7',
        type: 'REWARD',
        title: '+3 Sao Thi Đua Xuất Sắc',
        badge: '🌟',
        starPoints: 3,
        desc: 'Phần thưởng may mắn đặc biệt: Cộng ngay 3 sao vào bảng vàng thi đua!',
        color: 'from-violet-500 to-fuchsia-600',
      },
      {
        id: 'r8',
        type: 'REWARD',
        title: 'Phiếu Đổi Chỗ Ngồi Yêu Thích',
        badge: '🪑',
        starPoints: 1,
        desc: 'Được chọn ngồi cùng bạn thân hoặc vị trí yêu thích trong 1 buổi học.',
        color: 'from-teal-500 to-green-600',
      },
      {
        id: 'r9',
        type: 'REWARD',
        title: 'Làm Trợ Lý Cô Giáo 1 Buổi',
        badge: '🎖️',
        starPoints: 2,
        desc: 'Được giúp cô giáo phát phiếu bài tập và chấm điểm thi đua các tổ.',
        color: 'from-sky-500 to-blue-600',
      },
      {
        id: 'r10',
        type: 'REWARD',
        title: 'Lời Khen Danh Dự Trước Lớp',
        badge: '📢',
        starPoints: 1,
        desc: 'Cô giáo tuyên dương sự tiến bộ vượt bậc của em trước toàn thể lớp học!',
        color: 'from-red-500 to-orange-600',
      },
      {
        id: 'r11',
        type: 'REWARD',
        title: 'Cái Đập Tay High-Five & Lời Chúc',
        badge: '🖐️',
        starPoints: 1,
        desc: 'Cô giáo và các bạn cùng High-Five chúc mừng tinh thần học tập gương mẫu!',
        color: 'from-lime-500 to-emerald-600',
      },
      {
        id: 'r12',
        type: 'REWARD',
        title: '1 Món Quà Bút Chì May Mắn',
        badge: '✏️',
        starPoints: 1,
        desc: 'Nhận 1 cây bút chì / cục tẩy may mắn từ hộp quà bí mật của cô!',
        color: 'from-indigo-500 to-purple-600',
      },
    ],
  },

  // 2. THỬ THÁCH KHỞI ĐỘNG & VẬN ĐỘNG VUI
  {
    id: 'pack-challenges',
    title: 'Thử Thách Khởi Động & Vận Động Vui',
    description: 'Thử thách hoạt náo, ca hát, vận động giải phóng năng lượng đầu giờ hoặc chuyển tiết.',
    category: 'CHALLENGE',
    icon: '🎯',
    items: [
      {
        id: 'c1',
        type: 'CHALLENGE',
        title: 'Hát 1 Câu Trong Bài Hát Em Thích',
        badge: '🎤',
        starPoints: 2,
        desc: 'Tự tin đứng dậy hát vang 1 câu hoặc 1 đoạn bài hát thiếu nhi yêu thích!',
        answer: 'Thử thách thành công khi học sinh hát tự tin trước lớp.',
        color: 'from-rose-500 to-pink-500',
      },
      {
        id: 'c2',
        type: 'CHALLENGE',
        title: 'Bắt Chước Tiếng Kêu Chú Mèo / Gà Trống',
        badge: '🐱',
        starPoints: 2,
        desc: 'Làm động tác và phát ra tiếng kêu ngộ nghĩnh của một loài vật em thích!',
        answer: 'Tiếng kêu: "Meo meo~" hoặc "Ò ó o o~" kèm điệu bộ dễ thương.',
        color: 'from-amber-500 to-orange-500',
      },
      {
        id: 'c3',
        type: 'CHALLENGE',
        title: 'Nhảy Vũ Điệu Sôi Động Trong 15 Giây',
        badge: '🕺',
        starPoints: 2,
        desc: 'Cùng cả lớp vỗ tay theo nhịp để em nhảy 1 điệu nhảy vui nhộn 15s!',
        answer: 'Vận động theo điệu nhạc hoặc nhịp vỗ tay của cả lớp.',
        color: 'from-purple-500 to-indigo-500',
      },
      {
        id: 'c4',
        type: 'CHALLENGE',
        title: 'Kể 1 Câu Đố Cho Cả Lớp Cùng Giải',
        badge: '🧩',
        starPoints: 2,
        desc: 'Đố cả lớp 1 câu đố vui dân gian hoặc câu đố mẹo mà em biết!',
        answer: 'Cả lớp cùng suy nghĩ và giơ tay giải câu đố.',
        color: 'from-blue-500 to-cyan-500',
      },
      {
        id: 'c5',
        type: 'CHALLENGE',
        title: 'Làm Mặt Cười Hài Hước Nhất Lớp',
        badge: '🎭',
        starPoints: 2,
        desc: 'Tạo 1 dáng mặt hề ngộ nghĩnh khiến 3 bạn xung quanh bật cười!',
        answer: 'Tạo không khí vui vẻ, thoải mái cho cả lớp học.',
        color: 'from-yellow-400 to-amber-500',
      },
      {
        id: 'c6',
        type: 'CHALLENGE',
        title: 'Đọc Thuộc Lòng 1 Khổ Thơ Hoặc Bảng Nhân 8',
        badge: '📖',
        starPoints: 2,
        desc: 'Đọc thật diễn cảm 1 đoạn thơ trong sách Tiếng Việt hoặc đọc nhẩm bảng nhân 8!',
        answer: 'Đọc to, rõ ràng và trôi chảy.',
        color: 'from-emerald-500 to-teal-500',
      },
      {
        id: 'c7',
        type: 'CHALLENGE',
        title: 'Xoay Khớp Vận Động Khỏe Khoắn 20 Giây',
        badge: '🤸',
        starPoints: 2,
        desc: 'Làm mẫu động tác vươn vai, xoay cổ tay và hít thở sâu để cả lớp làm theo!',
        answer: 'Cả lớp cùng đứng dậy vận động giải tỏa mệt mỏi.',
        color: 'from-teal-500 to-green-600',
      },
      {
        id: 'c8',
        type: 'CHALLENGE',
        title: 'Bắt Tay & Khen Ngợi 3 Bạn Xung Quanh',
        badge: '🤝',
        starPoints: 2,
        desc: 'Quay sang 3 bạn gần nhất, bắt tay và nói 1 lời khen chân thành!',
        answer: 'Lan tỏa tinh thần đoàn kết và yêu thương bạn bè.',
        color: 'from-sky-500 to-blue-600',
      },
      {
        id: 'c9',
        type: 'CHALLENGE',
        title: 'Kể Tên 5 Con Vật Sống Dưới Nước (10 Giây)',
        badge: '🐬',
        starPoints: 2,
        desc: 'Kể thật nhanh tên 5 loài động vật dưới nước trước khi cô đếm hết 10 giây!',
        answer: 'Gợi ý: Cá heo, cá voi, rùa biển, tôm, cua, mực, bạch tuộc...',
        color: 'from-cyan-500 to-blue-600',
      },
      {
        id: 'c10',
        type: 'CHALLENGE',
        title: 'Đếm Ngược Từ 20 Về 1 Thật Nhanh',
        badge: '⏱️',
        starPoints: 2,
        desc: 'Đếm ngược 20, 19, 18... về 1 thật tốc độ và chính xác!',
        answer: '20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1.',
        color: 'from-orange-500 to-red-600',
      },
      {
        id: 'c11',
        type: 'CHALLENGE',
        title: 'Tạo Dáng Siêu Nhân Tự Tin Trên Bục Giảng',
        badge: '🦸',
        starPoints: 2,
        desc: 'Đứng tư thế siêu anh hùng dũng mãnh và hô vang khẩu hiệu lớp ta!',
        answer: 'Tư thế tràn đầy tự tin và quyết tâm học tốt!',
        color: 'from-indigo-500 to-purple-600',
      },
      {
        id: 'c12',
        type: 'CHALLENGE',
        title: 'Đứng 1 Chân Giữ Thăng Bằng Trong 10 Giây',
        badge: '🦩',
        starPoints: 2,
        desc: 'Đứng thăng bằng kiểu chim hồng hạc 1 chân không lung lay trong 10s!',
        answer: 'Giữ thăng bằng vững vàng trong tiếng đếm của cả lớp.',
        color: 'from-pink-500 to-rose-600',
      },
    ],
  },

  // 3. ĐỐ VUI KIẾN THỨC & TRÍ TUỆ NHANH
  {
    id: 'pack-quizzes',
    title: 'Đố Vui Kiến Thức & Trí Tuệ Nhanh',
    description: 'Câu hỏi đố vui Toán học, Tiếng Việt, Tự nhiên Xã hội và câu đố mẹo rèn luyện tư duy.',
    category: 'QUIZ',
    icon: '🧠',
    items: [
      {
        id: 'q1',
        type: 'QUESTION',
        title: 'Toán Đố: 8 × 7 = ?',
        badge: '🔢',
        starPoints: 2,
        desc: 'Tính nhẩm nhanh kết quả của phép nhân 8 nhân 7 bằng bao nhiêu?',
        answer: 'Đáp án: 8 × 7 = 56.',
        color: 'from-blue-500 to-indigo-600',
      },
      {
        id: 'q2',
        type: 'QUESTION',
        title: 'Từ Trái Nghĩa Với "Dũng Cảm"?',
        badge: '📚',
        starPoints: 2,
        desc: 'Tìm 1 từ ngữ có nghĩa trái ngược hoàn toàn với từ "Dũng cảm"?',
        answer: 'Đáp án: Hèn nhát / Nhút nhát / Hèn yếu.',
        color: 'from-emerald-500 to-teal-600',
      },
      {
        id: 'q3',
        type: 'QUESTION',
        title: 'Đố Mẹo: Càng Lấy Đi Càng To Ra?',
        badge: '💡',
        starPoints: 2,
        desc: 'Cái gì mà bạn càng lấy đi nhiều thì nó lại càng trở nên to ra?',
        answer: 'Đáp án: Cái hố / Cái lỗ (hoặc Tuổi tác).',
        color: 'from-amber-500 to-orange-500',
      },
      {
        id: 'q4',
        type: 'QUESTION',
        title: 'Mặt Trời Mọc & Lặn Hướng Nào?',
        badge: '☀️',
        starPoints: 2,
        desc: 'Mặt Trời mọc ở hướng nào vào buổi sáng và lặn ở hướng nào buổi chiều?',
        answer: 'Đáp án: Mọc ở hướng ĐÔNG, lặn ở hướng TÂY.',
        color: 'from-yellow-400 to-amber-500',
      },
      {
        id: 'q5',
        type: 'QUESTION',
        title: 'Từ Chỉ Hoạt Động Trong Câu?',
        badge: '📝',
        starPoints: 2,
        desc: 'Trong câu "Bác nông dân đang cày ruộng", từ nào là từ chỉ hoạt động?',
        answer: 'Đáp án: Từ "cày" (hoặc "cày ruộng").',
        color: 'from-rose-500 to-pink-500',
      },
      {
        id: 'q6',
        type: 'QUESTION',
        title: '1 Giờ Có Bao Nhiêu Phút?',
        badge: '⏰',
        starPoints: 2,
        desc: '1 giờ có bao nhiêu phút? Và 1 ngày có bao nhiêu giờ?',
        answer: 'Đáp án: 1 giờ = 60 phút; 1 ngày = 24 giờ.',
        color: 'from-purple-500 to-indigo-600',
      },
      {
        id: 'q7',
        type: 'QUESTION',
        title: 'Con Gì Mũi Dài Mà Không Mồm Ở Mũi?',
        badge: '🐘',
        starPoints: 2,
        desc: 'Đố vui: Con gì có chiếc mũi rất dài, có thể hút nước và mang vác đồ?',
        answer: 'Đáp án: Con Voi.',
        color: 'from-teal-500 to-emerald-600',
      },
      {
        id: 'q8',
        type: 'QUESTION',
        title: 'Nước Sôi Ở Bao Nhiêu Độ C?',
        badge: '💧',
        starPoints: 2,
        desc: 'Ở điều kiện bình thường, nước nguyên chất sôi ở nhiệt độ bao nhiêu?',
        answer: 'Đáp án: 100°C (và đóng băng ở 0°C).',
        color: 'from-cyan-500 to-blue-600',
      },
      {
        id: 'q9',
        type: 'QUESTION',
        title: 'Tiếng Anh: "Quả Táo" Đọc Là Gì?',
        badge: '🍎',
        starPoints: 2,
        desc: 'Trong Tiếng Anh, từ quả táo viết và phát âm như thế nào?',
        answer: 'Đáp án: Apple (/ˈæp.əl/).',
        color: 'from-red-500 to-rose-600',
      },
      {
        id: 'q10',
        type: 'QUESTION',
        title: 'Toán: Một Nửa Của 100 Cộng Thêm 25?',
        badge: '➕',
        starPoints: 2,
        desc: 'Một nửa của 100 là bao nhiêu, sau đó cộng thêm 25 thì bằng bao nhiêu?',
        answer: 'Đáp án: 50 + 25 = 75.',
        color: 'from-violet-500 to-purple-600',
      },
      {
        id: 'q11',
        type: 'QUESTION',
        title: 'Bác Hồ Đọc Tuyên Ngôn Độc Lập Ngày Nào?',
        badge: '🇻🇳',
        starPoints: 2,
        desc: 'Ngày Quốc khánh nước Cộng hòa Xã hội Chủ nghĩa Việt Nam là ngày nào?',
        answer: 'Đáp án: Ngày 2 tháng 9 năm 1945 tại Quảng trường Ba Đình.',
        color: 'from-amber-600 to-red-600',
      },
      {
        id: 'q12',
        type: 'QUESTION',
        title: 'Thành Ngữ: "Học Đi Đôi Với ..."?',
        badge: '🎯',
        starPoints: 2,
        desc: 'Điền từ còn thiếu vào câu thành ngữ quen thuộc: "Học đi đôi với ..."?',
        answer: 'Đáp án: "Học đi đôi với HÀNH".',
        color: 'from-lime-500 to-emerald-600',
      },
    ],
  },

  // 4. HỘP QUÀ KỲ DIỆU (KẾT HỢP QUÀ THƯỞNG + THỬ THÁCH)
  {
    id: 'pack-mixed',
    title: 'Hộp Quà Kỳ Diệu (Thưởng + Thử Thách Bất Ngờ)',
    description: 'Hỗn hợp hồi hộp 50/50 giữa phần thưởng may mắn cực xịn và thử thách đố vui kích thích.',
    category: 'MIXED',
    icon: '✨',
    items: [
      {
        id: 'm1',
        type: 'REWARD',
        title: 'Trúng Thưởng: +3 Sao Thi Đua',
        badge: '🌟',
        starPoints: 3,
        desc: 'Bạn nhận được giải thưởng may mắn lớn: +3 sao vào sổ nề nếp!',
        color: 'from-amber-500 to-orange-500',
      },
      {
        id: 'm2',
        type: 'CHALLENGE',
        title: 'Thử Thách: Hát 1 Đoạn Điệp Khúc',
        badge: '🎤',
        starPoints: 2,
        desc: 'Hát thật vang 1 đoạn bài hát thiếu nhi yêu thích trước cả lớp!',
        answer: 'Hát tự tin, cả lớp cùng vỗ tay hưởng ứng.',
        color: 'from-rose-500 to-pink-500',
      },
      {
        id: 'm3',
        type: 'REWARD',
        title: 'Trúng Thưởng: Miễn Trực Nhật 1 Buổi',
        badge: '🎟️',
        starPoints: 1,
        desc: 'Được miễn nhiệm vụ quét lớp và kê bàn ghế trong 1 buổi trực nhật.',
        color: 'from-blue-500 to-cyan-500',
      },
      {
        id: 'm4',
        type: 'QUESTION',
        title: 'Đố Vui: 9 × 6 = ?',
        badge: '🔢',
        starPoints: 2,
        desc: 'Tính nhẩm nhanh bảng nhân 9: 9 nhân 6 bằng bao nhiêu?',
        answer: 'Đáp án: 9 × 6 = 54.',
        color: 'from-purple-500 to-indigo-500',
      },
      {
        id: 'm5',
        type: 'REWARD',
        title: 'Trúng Thưởng: Chọn Bài Hát Giải Lao',
        badge: '🎵',
        starPoints: 1,
        desc: 'Được chọn bài hát yêu thích mở trong giờ nghỉ giải lao của lớp!',
        color: 'from-emerald-500 to-teal-500',
      },
      {
        id: 'm6',
        type: 'CHALLENGE',
        title: 'Thử Thách: Bắt Chước Tiếng Gà Gáy',
        badge: '🐔',
        starPoints: 2,
        desc: 'Làm động tác đập cánh và gáy vang "Ò ó o o" đánh thức cả lớp!',
        answer: 'Tạo tiếng cười vui vẻ cho cả lớp học.',
        color: 'from-yellow-400 to-amber-500',
      },
      {
        id: 'm7',
        type: 'REWARD',
        title: 'Trúng Thưởng: Sticker Khen Thưởng Xinh',
        badge: '🏷️',
        starPoints: 1,
        desc: 'Nhận 1 sticker siêu đáng yêu từ bộ sưu tập của cô giáo!',
        color: 'from-violet-500 to-fuchsia-600',
      },
      {
        id: 'm8',
        type: 'QUESTION',
        title: 'Đố Mẹo: Tháng Nào Có 28 Ngày?',
        badge: '📅',
        starPoints: 2,
        desc: 'Trong một năm, tháng nào có 28 ngày?',
        answer: 'Đáp án: TẤT CẢ các tháng đều có ngày thứ 28!',
        color: 'from-teal-500 to-green-600',
      },
      {
        id: 'm9',
        type: 'REWARD',
        title: 'Trúng Thưởng: Làm Quản Ca 1 Buổi',
        badge: '👑',
        starPoints: 1,
        desc: 'Được vinh dự lên bục giảng bắt nhịp cho cả lớp hát đầu giờ!',
        color: 'from-sky-500 to-blue-600',
      },
      {
        id: 'm10',
        type: 'CHALLENGE',
        title: 'Thử Thách: Kể Tên 3 Bạn Thân Nhất',
        badge: '🥰',
        starPoints: 2,
        desc: 'Kể tên 3 bạn trong lớp mà em quý mến nhất và gửi lời cảm ơn đến các bạn!',
        answer: 'Gắn kết tình bạn trong tập thể lớp học.',
        color: 'from-red-500 to-orange-600',
      },
      {
        id: 'm11',
        type: 'REWARD',
        title: 'Trúng Thưởng: Tràng Pháo Tay Siêu To',
        badge: '👏',
        starPoints: 1,
        desc: 'Cả lớp đứng dậy vỗ tay chúc mừng em thật nồng nhiệt!',
        color: 'from-lime-500 to-emerald-600',
      },
      {
        id: 'm12',
        type: 'QUESTION',
        title: 'Đố Vui: Thủ Đô Nước Việt Nam Là Gì?',
        badge: '🏛️',
        starPoints: 2,
        desc: 'Thủ đô ngàn năm văn hiến của nước ta tên là thành phố nào?',
        answer: 'Đáp án: Thủ đô HÀ NỘI.',
        color: 'from-indigo-500 to-purple-600',
      },
    ],
  },
];

/**
 * Trả về danh sách n item cho hộp quà dựa theo pack và số lượng boxCount
 */
export function getItemsForChestCount(
  pack: MysteryChestPack,
  count: number
): MysteryChestItem[] {
  const items = [...pack.items];
  
  if (items.length === 0) {
    return Array.from({ length: count }, (_, i) => ({
      id: `default_${i + 1}`,
      type: 'REWARD' as const,
      title: `Hộp Quà May Mắn #${i + 1}`,
      badge: '🎁',
      starPoints: 1,
      desc: 'Phần thưởng bí mật từ cô giáo!',
      color: CHEST_GRADIENT_COLORS[i % CHEST_GRADIENT_COLORS.length],
    }));
  }

  // Nếu pack có ít hơn count, lặp lại hoặc tạo thêm
  if (items.length < count) {
    const result: MysteryChestItem[] = [];
    let idx = 0;
    while (result.length < count) {
      const baseItem = items[idx % items.length];
      result.push({
        ...baseItem,
        id: `${baseItem.id}_copy_${result.length + 1}`,
      });
      idx++;
    }
    return result;
  }
  
  return items.slice(0, count);
}

/**
 * Xáo trộn vị trí mảng ngẫu nhiên (Fisher-Yates)
 */
export function shuffleChestItems(items: MysteryChestItem[]): MysteryChestItem[] {
  const result = [...items];
  for (let i = result.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [result[i], result[j]] = [result[j], result[i]];
  }
  return result;
}
