import { GradeLevel, TermType } from '@/types';

export type TT27Level = 'MUC_1' | 'MUC_2' | 'MUC_3';
export type QuestionType = 'MULTIPLE_CHOICE' | 'ESSAY';

export interface ExamQuestion {
  id: string;
  subjectCode: string;
  grade: GradeLevel;
  term: TermType;
  strand: string;
  level: TT27Level;
  type: QuestionType;
  content: string;
  options?: string[];
  correctAnswer: string;
  points: number;
  explanation?: string;
  createdAt: string;
}

export const INITIAL_QUESTION_BANK: ExamQuestion[] = [
  {
    id: 'q-toan-01',
    subjectCode: 'TOAN',
    grade: 4,
    term: 'GIUA_HK1',
    strand: 'Số và phép tính',
    level: 'MUC_1',
    type: 'MULTIPLE_CHOICE',
    content: 'Số gồm 5 trăm nghìn, 7 chục nghìn và 2 đơn vị được viết là:',
    options: ['A. 570 002', 'B. 57 002', 'C. 507 002', 'D. 570 200'],
    correctAnswer: 'A',
    points: 1.0,
    explanation: '5 trăm nghìn = 500 000, 7 chục nghìn = 70 000, 2 đơn vị = 2. Tổng là 570 002.',
    createdAt: '2026-08-28T08:00:00Z',
  },
  {
    id: 'q-toan-02',
    subjectCode: 'TOAN',
    grade: 4,
    term: 'GIUA_HK1',
    strand: 'Hình học và đo lường',
    level: 'MUC_1',
    type: 'MULTIPLE_CHOICE',
    content: 'Góc nào sau đây là góc nhọn?',
    options: ['A. Góc có số đo bằng 90°', 'B. Góc bé hơn góc vuông', 'C. Góc lớn hơn góc vuông', 'D. Góc bẹt'],
    correctAnswer: 'B',
    points: 1.0,
    explanation: 'Góc nhọn có đỉnh bé hơn 90° (bé hơn góc vuông).',
    createdAt: '2026-08-28T08:00:00Z',
  },
  {
    id: 'q-toan-03',
    subjectCode: 'TOAN',
    grade: 4,
    term: 'GIUA_HK1',
    strand: 'Số và phép tính',
    level: 'MUC_2',
    type: 'MULTIPLE_CHOICE',
    content: 'Trung bình cộng của ba số 35, 45 và 70 là:',
    options: ['A. 45', 'B. 50', 'C. 55', 'D. 60'],
    correctAnswer: 'B',
    points: 1.0,
    explanation: '(35 + 45 + 70) : 3 = 150 : 3 = 50.',
    createdAt: '2026-08-28T08:00:00Z',
  },
  {
    id: 'q-toan-04',
    subjectCode: 'TOAN',
    grade: 4,
    term: 'GIUA_HK1',
    strand: 'Hình học và đo lường',
    level: 'MUC_1',
    type: 'MULTIPLE_CHOICE',
    content: '3 tấn 25 kg = ............. kg. Số thích hợp điền vào chỗ chấm là:',
    options: ['A. 325', 'B. 3 025', 'C. 3 250', 'D. 30 025'],
    correctAnswer: 'B',
    points: 1.0,
    explanation: '1 tấn = 1 000 kg => 3 tấn 25 kg = 3 000 + 25 = 3 025 kg.',
    createdAt: '2026-08-28T08:00:00Z',
  },
  {
    id: 'q-toan-05',
    subjectCode: 'TOAN',
    grade: 4,
    term: 'GIUA_HK1',
    strand: 'Số và phép tính',
    level: 'MUC_2',
    type: 'ESSAY',
    content: 'Đặt tính rồi tính: a) 345 829 + 128 450 | b) 708 521 - 245 318 | c) 4 215 × 6 | d) 25 840 : 5',
    correctAnswer: 'a) 474 279 (0.5đ) | b) 463 203 (0.5đ) | c) 25 290 (0.5đ) | d) 5 168 (0.5đ)',
    points: 2.0,
    explanation: 'Mỗi phép tính đúng cho 0.5 điểm.',
    createdAt: '2026-08-28T08:00:00Z',
  },
  {
    id: 'q-toan-06',
    subjectCode: 'TOAN',
    grade: 4,
    term: 'GIUA_HK1',
    strand: 'Số và phép tính',
    level: 'MUC_2',
    type: 'ESSAY',
    content: 'Một mảnh đất hình chữ nhật có nửa chu vi là 120 m. Chiều dài hơn chiều rộng 30 m. Tính diện tích của mảnh đất đó?',
    correctAnswer: 'Chiều dài là: (120 + 30) : 2 = 75 m. Chiều rộng là: 120 - 75 = 45 m. Diện tích là: 75 × 45 = 3 375 m². Đáp số: 3 375 m²',
    points: 2.5,
    explanation: 'Tìm hai số khi biết tổng và hiệu: số lớn = (tổng + hiệu) : 2. Tính diện tích = dài × rộng.',
    createdAt: '2026-08-28T08:00:00Z',
  },
  {
    id: 'q-toan-07',
    subjectCode: 'TOAN',
    grade: 4,
    term: 'GIUA_HK1',
    strand: 'Số và phép tính',
    level: 'MUC_3',
    type: 'ESSAY',
    content: 'Tính bằng cách thuận tiện nhất: 125 × 38 + 125 × 62',
    correctAnswer: '= 125 × (38 + 62) = 125 × 100 = 12 500',
    points: 1.5,
    explanation: 'Áp dụng tính chất nhân một số với một tổng: a × b + a × c = a × (b + c).',
    createdAt: '2026-08-28T08:00:00Z',
  },
  {
    id: 'q-tv-01',
    subjectCode: 'TIENG_VIET',
    grade: 4,
    term: 'GIUA_HK1',
    strand: 'Luyện từ và câu',
    level: 'MUC_1',
    type: 'MULTIPLE_CHOICE',
    content: 'Từ nào dưới đây là từ ghép tổng hợp?',
    options: ['A. Xe đạp', 'B. Nhà cửa', 'C. Bút chì', 'D. Hoa hồng'],
    correctAnswer: 'B',
    points: 1.0,
    explanation: 'Nhà cửa là từ ghép tổng hợp chỉ chung nơi ở, các từ còn lại là từ ghép phân loại.',
    createdAt: '2026-08-28T08:00:00Z',
  },
  {
    id: 'q-tv-02',
    subjectCode: 'TIENG_VIET',
    grade: 4,
    term: 'GIUA_HK1',
    strand: 'Đọc hiểu văn bản',
    level: 'MUC_1',
    type: 'MULTIPLE_CHOICE',
    content: 'Nhân vật Dế Mèn trong tác phẩm Dế Mèn bênh vực kẻ yếu đã có hành động cao đẹp gì?',
    options: [
      'A. Xóa nợ và phá tan vòng vây mạng nhện bảo vệ chị Nhà Trò',
      'B. Bay đi chu du khắp thế giới',
      'C. Đánh nhau với bọ ngựa',
      'D. Đi tìm cỏ non để ăn'
    ],
    correctAnswer: 'A',
    points: 1.0,
    explanation: 'Dế Mèn đã ra tay bảo vệ chị Nhà Trò yếu ớt trước lũ nhện độc ác.',
    createdAt: '2026-08-28T08:00:00Z',
  },
  {
    id: 'q-tv-03',
    subjectCode: 'TIENG_VIET',
    grade: 4,
    term: 'GIUA_HK1',
    strand: 'Luyện từ và câu',
    level: 'MUC_2',
    type: 'MULTIPLE_CHOICE',
    content: 'Trong câu Mùa thu, bầu trời xanh trong vắt, cụm từ Mùa thu giữ chức vụ ngữ pháp gì?',
    options: ['A. Chủ ngữ', 'B. Vị ngữ', 'C. Trạng ngữ chỉ thời gian', 'D. Trạng ngữ chỉ nơi chốn'],
    correctAnswer: 'C',
    points: 1.0,
    explanation: 'Mùa thu bổ sung ý nghĩa thời gian cho câu nên là trạng ngữ chỉ thời gian.',
    createdAt: '2026-08-28T08:00:00Z',
  },
  {
    id: 'q-tv-04',
    subjectCode: 'TIENG_VIET',
    grade: 4,
    term: 'GIUA_HK1',
    strand: 'Luyện từ và câu',
    level: 'MUC_2',
    type: 'ESSAY',
    content: 'Tìm 2 danh từ chung và 2 danh từ riêng có trong đoạn văn sau: Bác Hồ kính yêu sinh ra tại làng Sen, thuộc tỉnh Nghệ An. Người dành trọn cuộc đời vì độc lập tự do cho Tổ quốc.',
    correctAnswer: '- Danh từ chung: làng, tỉnh, cuộc đời, độc lập, tự do, tổ quốc (Chọn 2 từ được 1.0đ). - Danh từ riêng: Bác Hồ, Sen, Nghệ An (Chọn 2 từ được 1.0đ).',
    points: 2.0,
    explanation: 'Danh từ riêng chỉ tên riêng của người, địa danh và được viết hoa.',
    createdAt: '2026-08-28T08:00:00Z',
  },
  {
    id: 'q-tv-05',
    subjectCode: 'TIENG_VIET',
    grade: 4,
    term: 'GIUA_HK1',
    strand: 'Tập làm văn',
    level: 'MUC_3',
    type: 'ESSAY',
    content: 'Viết một đoạn văn ngắn (từ 5 đến 7 câu) kể về một việc tốt em đã làm để giúp đỡ bạn bè hoặc người thân trong gia đình.',
    correctAnswer: 'Yêu cầu: Viết đúng độ dài 5-7 câu, nội dung kể việc tốt rõ ràng, câu văn gãy gọn, không sai chính tả, thể hiện tình cảm chân thành (5.0đ).',
    points: 5.0,
    explanation: 'Đánh giá theo các tiêu chí: Đúng đề tài (2đ), diễn đạt mạch lạc (2đ), chính tả và sáng tạo (1đ).',
    createdAt: '2026-08-28T08:00:00Z',
  },
  {
    id: 'q-kh-01',
    subjectCode: 'KHOA_HOC',
    grade: 4,
    term: 'GIUA_HK1',
    strand: 'Chất và sự biến đổi của chất',
    level: 'MUC_1',
    type: 'MULTIPLE_CHOICE',
    content: 'Nước có tính chất nào sau đây?',
    options: [
      'A. Là chất lỏng trong suốt, không màu, không mùi, không vị, chảy từ cao xuống thấp',
      'B. Có hình dạng cố định và có màu trắng',
      'C. Không thể hòa tan được bất kỳ chất nào',
      'D. Có mùi thơm và vị ngọt'
    ],
    correctAnswer: 'A',
    points: 1.5,
    explanation: 'Nước là chất lỏng trong suốt, không màu, không mùi, không vị, không có hình dạng nhất định.',
    createdAt: '2026-08-28T08:00:00Z',
  },
  {
    id: 'q-kh-02',
    subjectCode: 'KHOA_HOC',
    grade: 4,
    term: 'GIUA_HK1',
    strand: 'Năng lượng & Đời sống',
    level: 'MUC_2',
    type: 'MULTIPLE_CHOICE',
    content: 'Để phòng tránh tai nạn đuối nước và bảo vệ nguồn nước sạch, chúng ta KHÔNG NÊN làm gì?',
    options: [
      'A. Tiết kiệm nước và khóa vòi sau khi dùng',
      'B. Xả rác thải và đổ chất độc hại xuống ao hồ, sông suối',
      'C. Khơi thông cống rãnh xung quanh nhà',
      'D. Mặc áo phao khi tham gia giao thông đường thủy'
    ],
    correctAnswer: 'B',
    points: 1.5,
    explanation: 'Xả rác thải xuống nguồn nước gây ô nhiễm môi trường nghiêm trọng.',
    createdAt: '2026-08-28T08:00:00Z',
  },
  {
    id: 'q-kh-03',
    subjectCode: 'KHOA_HOC',
    grade: 4,
    term: 'GIUA_HK1',
    strand: 'Chất và sự biến đổi của chất',
    level: 'MUC_3',
    type: 'ESSAY',
    content: 'Em hãy nêu 3 việc làm cụ thể của bản thân và gia đình để tiết kiệm nước và giữ sạch nguồn nước sinh hoạt hàng ngày?',
    correctAnswer: '1. Tắt vòi nước khi đang chải răng hoặc xà phòng (1.0đ) | 2. Tái sử dụng nước vo gạo, nước rửa rau để tưới cây (1.0đ) | 3. Không vứt rác bừa bãi xuống nguồn nước (1.0đ).',
    points: 3.0,
    explanation: 'Học sinh nêu được 3 hành động thiết thực, mỗi hành động đúng được 1.0 điểm.',
    createdAt: '2026-08-28T08:00:00Z',
  },
  {
    id: 'q-lsdl-01',
    subjectCode: 'LICH_SU_DIA_LY',
    grade: 4,
    term: 'GIUA_HK1',
    strand: 'Địa lý Việt Nam',
    level: 'MUC_1',
    type: 'MULTIPLE_CHOICE',
    content: 'Dãy núi nào cao nhất và đồ sộ nhất nước ta?',
    options: ['A. Dãy Trường Sơn', 'B. Dãy Hoàng Liên Sơn', 'C. Dãy Hoành Sơn', 'D. Dãy Bạch Mã'],
    correctAnswer: 'B',
    points: 1.5,
    explanation: 'Dãy Hoàng Liên Sơn nằm ở vùng Trung du và miền núi Bắc Bộ có đỉnh Fansipan cao 3 143 m.',
    createdAt: '2026-08-28T08:00:00Z',
  },
  {
    id: 'q-lsdl-02',
    subjectCode: 'LICH_SU_DIA_LY',
    grade: 4,
    term: 'GIUA_HK1',
    strand: 'Lịch sử Việt Nam',
    level: 'MUC_2',
    type: 'MULTIPLE_CHOICE',
    content: 'Nhà nước đầu tiên trong lịch sử dân tộc Việt Nam có tên là gì?',
    options: ['A. Văn Lang (thời các Vua Hùng)', 'B. Âu Lạc', 'C. Đại Cồ Việt', 'D. Đại Việt'],
    correctAnswer: 'A',
    points: 1.5,
    explanation: 'Nhà nước Văn Lang do các Vua Hùng dựng nên vào khoảng thế kỷ VII trước Công nguyên.',
    createdAt: '2026-08-28T08:00:00Z',
  },
  {
    id: 'q-lsdl-03',
    subjectCode: 'LICH_SU_DIA_LY',
    grade: 4,
    term: 'GIUA_HK1',
    strand: 'Lịch sử Việt Nam',
    level: 'MUC_3',
    type: 'ESSAY',
    content: 'Câu ca dao sau gợi nhớ đến ngày lễ trọng đại nào của dân tộc ta? Em cần làm gì để thể hiện lòng biết ơn các thế hệ cha ông đi trước? Dù ai đi ngược về xuôi - Nhớ ngày Giỗ Tổ mùng mười tháng ba',
    correctAnswer: '- Câu ca dao nhắc đến: Ngày Giỗ Tổ Hùng Vương (10/3 Âm lịch) tại Đền Hùng, Phú Thọ (1.0đ). - Hành động của học sinh: Chăm ngoan học giỏi, tìm hiểu lịch sử dân tộc, giữ gìn và phát huy truyền thống Uống nước nhớ nguồn (2.0đ).',
    points: 3.0,
    explanation: 'Đánh giá sự hiểu biết về ngày lễ cội nguồn và thái độ tôn kính lịch sử dân tộc.',
    createdAt: '2026-08-28T08:00:00Z',
  }
];
