import { QuizPack, GradeLevel } from '@/types';

export const DEFAULT_QUIZ_PACKS: QuizPack[] = [
  // 1. TOÁN HỌC KHỐI 4 - 5
  {
    id: 'pack-math-45',
    title: 'Toán Tư Duy & Tính Nhẩm Siêu Tốc (Khối 4 - 5)',
    description: 'Thử thách phép tính nhẩm, phân số, trung bình cộng và toán có lời văn logic.',
    subjectCode: 'TOAN',
    grade: 4,
    category: 'MATH',
    questions: [
      {
        id: 'm1',
        question: 'Tìm trung bình cộng của ba số: 15, 25 và 50 là bao nhiêu?',
        options: ['A. 25', 'B. 30', 'C. 35', 'D. 40'],
        correctIndex: 1,
        explanation: 'Tổng 3 số là 15 + 25 + 50 = 90. Trung bình cộng là 90 : 3 = 30.',
        timeLimit: 15,
      },
      {
        id: 'm2',
        question: 'Một hình chữ nhật có chiều dài 12m, chiều rộng bằng 1/2 chiều dài. Diện tích là:',
        options: ['A. 36 m²', 'B. 48 m²', 'C. 72 m²', 'D. 96 m²'],
        correctIndex: 2,
        explanation: 'Chiều rộng là 12 : 2 = 6m. Diện tích = 12 × 6 = 72 m².',
        timeLimit: 15,
      },
      {
        id: 'm3',
        question: 'Rút gọn phân số 24/36 về phân số tối giản ta được:',
        options: ['A. 12/18', 'B. 6/9', 'C. 2/3', 'D. 3/4'],
        correctIndex: 2,
        explanation: 'Chia cả tử và mẫu cho 12: 24:12 = 2, 36:12 = 3 => 2/3.',
        timeLimit: 12,
      },
      {
        id: 'm4',
        question: 'Số nào sau đây vừa chia hết cho 2 vừa chia hết cho 5?',
        options: ['A. 135', 'B. 240', 'C. 314', 'D. 425'],
        correctIndex: 1,
        explanation: 'Số vừa chia hết cho 2 vừa chia hết cho 5 phải có chữ số tận cùng là 0 => 240.',
        timeLimit: 10,
      },
      {
        id: 'm5',
        question: 'Tổng của hai số là 80, hiệu là 20. Số lớn là:',
        options: ['A. 40', 'B. 50', 'C. 60', 'D. 70'],
        correctIndex: 1,
        explanation: 'Số lớn = (Tổng + Hiệu) : 2 = (80 + 20) : 2 = 50.',
        timeLimit: 15,
      },
      {
        id: 'm6',
        question: 'Một lớp học có 40 học sinh, trong đó 60% là học sinh nữ. Số học sinh nam là:',
        options: ['A. 16 bạn', 'B. 20 bạn', 'C. 24 bạn', 'D. 28 bạn'],
        correctIndex: 0,
        explanation: 'Số bạn nam chiếm 40%. Số học sinh nam là 40 × 40% = 16 bạn.',
        timeLimit: 15,
      },
    ],
  },

  // 2. TOÁN HỌC KHỐI 1 - 2 - 3
  {
    id: 'pack-math-123',
    title: 'Bảng Cửu Chương & Phép Tính Nhanh (Khối 1 - 3)',
    description: 'Rèn luyện bảng nhân chia 6, 7, 8, 9 và phép cộng trừ có nhớ trong phạm vi 100.',
    subjectCode: 'TOAN',
    grade: 3,
    category: 'MATH',
    questions: [
      {
        id: 'm123_1',
        question: 'Kết quả của phép tính: 7 × 8 + 14 là:',
        options: ['A. 60', 'B. 70', 'C. 72', 'D. 68'],
        correctIndex: 1,
        explanation: '7 × 8 = 56. 56 + 14 = 70.',
        timeLimit: 12,
      },
      {
        id: 'm123_2',
        question: 'Số gồm 5 trăm, 0 chục và 8 đơn vị được viết là:',
        options: ['A. 58', 'B. 580', 'C. 508', 'D. 805'],
        correctIndex: 2,
        explanation: '5 trăm + 0 chục + 8 đơn vị = 508.',
        timeLimit: 10,
      },
      {
        id: 'm123_3',
        question: 'Mẹ mua 4 hộp bánh, mỗi hộp có 6 cái bánh. Mẹ cho con 5 cái. Mẹ còn lại số cái bánh là:',
        options: ['A. 19 cái', 'B. 24 cái', 'C. 20 cái', 'D. 18 cái'],
        correctIndex: 0,
        explanation: 'Tổng số bánh là 4 × 6 = 24 cái. Còn lại: 24 - 5 = 19 cái.',
        timeLimit: 15,
      },
      {
        id: 'm123_4',
        question: 'Một ngày có bao nhiêu giờ?',
        options: ['A. 12 giờ', 'B. 24 giờ', 'C. 48 giờ', 'D. 60 giờ'],
        correctIndex: 1,
        explanation: 'Một ngày có 24 giờ.',
        timeLimit: 10,
      },
      {
        id: 'm123_5',
        question: 'Kết quả của phép chia 72 : 9 là:',
        options: ['A. 6', 'B. 7', 'C. 8', 'D. 9'],
        correctIndex: 2,
        explanation: '9 × 8 = 72 => 72 : 9 = 8.',
        timeLimit: 10,
      },
    ],
  },

  // 3. TIẾNG VIỆT - VUA TIẾNG VIỆT TIỂU HỌC
  {
    id: 'pack-viet-all',
    title: 'Vua Tiếng Việt — Từ Ngữ & Thành Ngữ (Khối 3 - 5)',
    description: 'Câu đố từ đồng nghĩa, trái nghĩa, thành ngữ tục ngữ và các biện pháp tu từ nghệ thuật.',
    subjectCode: 'TIENG_VIET',
    grade: 4,
    category: 'VIETNAMESE',
    questions: [
      {
        id: 'v1',
        question: 'Cặp từ nào dưới đây là cặp từ ĐỒNG NGHĨA?',
        options: ['A. Chăm chỉ — Lười biếng', 'B. Siêng năng — Cần cù', 'C. Cao vút — Thấp tè', 'D. Thông minh — Ngốc nghếch'],
        correctIndex: 1,
        explanation: '"Siêng năng" và "Cần cù" đều chỉ đức tính chăm làm việc.',
        timeLimit: 12,
      },
      {
        id: 'v2',
        question: 'Điền từ còn thiếu vào câu thành ngữ: "Uống nước nhớ ..."',
        options: ['A. Nguồn', 'B. Dòng', 'C. Suối', 'D. Sông'],
        correctIndex: 0,
        explanation: 'Thành ngữ: "Uống nước nhớ nguồn".',
        timeLimit: 10,
      },
      {
        id: 'v3',
        question: 'Câu văn: "Mặt trời như một quả cầu lửa khổng lồ từ từ nhô lên" sử dụng biện pháp tu từ nào?',
        options: ['A. Nhân hóa', 'B. So sánh', 'C. Ẩn dụ', 'D. Điệp từ'],
        correctIndex: 1,
        explanation: 'Câu văn sử dụng từ so sánh "như" để đối chiếu mặt trời với quả cầu lửa.',
        timeLimit: 12,
      },
      {
        id: 'v4',
        question: 'Từ nào sau đây viết ĐÚNG chính tả?',
        options: ['A. Sắp xếp', 'B. Xắp xếp', 'C. Xắp sếp', 'D. Sắp sếp'],
        correctIndex: 0,
        explanation: '"Sắp xếp" là cách viết đúng chính tả tiếng Việt.',
        timeLimit: 10,
      },
      {
        id: 'v5',
        question: 'Trong câu: "Mẹ em là bác sĩ", bộ phận vị ngữ là:',
        options: ['A. Mẹ em', 'B. Là bác sĩ', 'C. Bác sĩ', 'D. Mẹ'],
        correctIndex: 1,
        explanation: 'Câu kể "Ai là gì?": Chủ ngữ là "Mẹ em", Vị ngữ là "là bác sĩ".',
        timeLimit: 12,
      },
      {
        id: 'v6',
        question: 'Từ nào sau đây là TỪ LÁY?',
        options: ['A. Hoa hồng', 'B. Xanh ngắt', 'C. Róc rách', 'D. Cây cối'],
        correctIndex: 2,
        explanation: '"Róc rách" là từ láy âm đầu, mô tả tiếng nước chảy.',
        timeLimit: 12,
      },
    ],
  },

  // 4. TIẾNG ANH - ENGLISH CHAMPION
  {
    id: 'pack-eng-all',
    title: 'English Challenge — Từ Vựng & Giao Tiếp',
    description: 'Trắc nghiệm từ vựng vui nhộn, động vật, trường học và câu đố tiếng Anh tiểu học.',
    subjectCode: 'TIENG_ANH',
    grade: 'ALL',
    category: 'ENGLISH',
    questions: [
      {
        id: 'e1',
        question: 'Which animal is known as the "King of the Jungle"?',
        options: ['A. Elephant 🐘', 'B. Lion 🦁', 'C. Monkey 🐵', 'D. Tiger 🐯'],
        correctIndex: 1,
        explanation: 'The Lion 🦁 is commonly called the King of the Jungle.',
        timeLimit: 12,
      },
      {
        id: 'e2',
        question: 'What color do you get when you mix RED and YELLOW?',
        options: ['A. Green 🟢', 'B. Purple 🟣', 'C. Orange 🟠', 'D. Pink 🌸'],
        correctIndex: 2,
        explanation: 'Red + Yellow = Orange 🟠.',
        timeLimit: 10,
      },
      {
        id: 'e3',
        question: 'How many days are there in a week?',
        options: ['A. 5 days', 'B. 6 days', 'C. 7 days', 'D. 8 days'],
        correctIndex: 2,
        explanation: 'A week has 7 days (Monday through Sunday).',
        timeLimit: 10,
      },
      {
        id: 'e4',
        question: 'Choose the correct opposite of "BIG":',
        options: ['A. Tall', 'B. Small', 'C. Long', 'D. Heavy'],
        correctIndex: 1,
        explanation: 'The opposite of BIG is SMALL.',
        timeLimit: 10,
      },
      {
        id: 'e5',
        question: 'Where do we borrow books at school?',
        options: ['A. Canteen', 'B. Library', 'C. Playground', 'D. Gym'],
        correctIndex: 1,
        explanation: 'We borrow books at the Library.',
        timeLimit: 12,
      },
    ],
  },

  // 5. KHOA HỌC & LỊCH SỬ - ĐỊA LÝ VIỆT NAM
  {
    id: 'pack-science-social',
    title: 'Em Yêu Khoa Học & Non Sông Đất Nước',
    description: 'Khám phá thế giới tự nhiên, danh lam thắng cảnh và truyền thống lịch sử vẻ vang.',
    subjectCode: 'KHOA_HOC',
    grade: 'ALL',
    category: 'SCIENCE_SOCIAL',
    questions: [
      {
        id: 's1',
        question: 'Đỉnh núi nào được mệnh danh là "Nóc nhà Đông Dương" nằm ở nước ta?',
        options: ['A. Núi Bà Đen', 'B. Núi Fansipan', 'C. Núi Bạch Mộc Lương Tử', 'D. Núi Yên Tử'],
        correctIndex: 1,
        explanation: 'Đỉnh Fansipan cao 3.143m tại Lào Cai là đỉnh núi cao nhất Việt Nam và Đông Dương.',
        timeLimit: 15,
      },
      {
        id: 's2',
        question: 'Bộ phận nào của cây có chức năng chính là quang hợp và tổng hợp chất dinh dưỡng?',
        options: ['A. Rễ cây', 'B. Thân cây', 'C. Lá cây', 'D. Hoa'],
        correctIndex: 2,
        explanation: 'Lá cây chứa chất diệp lục giúp cây quang hợp dưới ánh sáng mặt trời.',
        timeLimit: 12,
      },
      {
        id: 's3',
        question: 'Ai là người lãnh đạo nhân dân đánh tan quân Nam Hán trên sông Bạch Đằng năm 938?',
        options: ['A. Đinh Bộ Lĩnh', 'B. Ngô Quyền', 'C. Lý Thường Kiệt', 'D. Trần Hưng Đạo'],
        correctIndex: 1,
        explanation: 'Ngô Quyền dùng kế cắm cọc gỗ trên sông Bạch Đằng đánh tan quân Nam Hán năm 938.',
        timeLimit: 15,
      },
      {
        id: 's4',
        question: 'Nước tồn tại ở mấy thể trong tự nhiên?',
        options: ['A. 2 thể', 'B. 3 thể (Rắn, Lỏng, Khí)', 'C. 4 thể', 'D. 1 thể'],
        correctIndex: 1,
        explanation: 'Nước tồn tại ở 3 thể: thể lỏng (nước), thể rắn (băng/đá), thể khí (hơi nước).',
        timeLimit: 12,
      },
      {
        id: 's5',
        question: 'Thủ đô của nước Cộng hòa Xã hội Chủ nghĩa Việt Nam là thành phố nào?',
        options: ['A. Đà Nẵng', 'B. TP. Hồ Chí Minh', 'C. Hà Nội', 'D. Hải Phòng'],
        correctIndex: 2,
        explanation: 'Hà Nội là thủ đô ngàn năm văn hiến của nước Việt Nam.',
        timeLimit: 10,
      },
    ],
  },

  // 6. ĐỐ VUI TRÍ TUỆ KHỞI ĐỘNG & NẠP NĂNG LƯỢNG
  {
    id: 'pack-trivia-fun',
    title: 'Đố Vui Dân Gian & Tư Duy Nhanh Trí',
    description: 'Các câu đố mẹo vui nhộn giúp học sinh hào hứng và rèn luyện tư duy phản biện.',
    subjectCode: 'HOAT_DONG_TRAI_NGHIEM',
    grade: 'ALL',
    category: 'TRIVIA_LOGIC',
    questions: [
      {
        id: 't1',
        question: 'Cái gì chặt không đứt, bứt không rời, phơi không khô, đốt không cháy?',
        options: ['A. Hòn đá', 'B. Nước', 'C. Khói', 'D. Không khí'],
        correctIndex: 1,
        explanation: 'Đó chính là dòng NƯỚC.',
        timeLimit: 12,
      },
      {
        id: 't2',
        question: 'Con gì đầu dê mình ốc?',
        options: ['A. Con dốc', 'B. Con dê biển', 'C. Con ốc vặn', 'D. Con ba ba'],
        correctIndex: 0,
        explanation: 'Chơi chữ dân gian: Con "dốc" (đầu chữ "dê" - d, mình chữ "ốc" - ôc).',
        timeLimit: 15,
      },
      {
        id: 't3',
        question: 'Cây gì nhiều mắt, thân hình gầy guộc, lá xòe như quạt, quả rụng thành cơm?',
        options: ['A. Cây chuối', 'B. Cây dừa', 'C. Cây cau', 'D. Cây tre'],
        correctIndex: 1,
        explanation: 'Đó là CÂY DỪA (cơm dừa, nước dừa).',
        timeLimit: 15,
      },
      {
        id: 't4',
        question: 'Trên nhấp dưới giật là đang làm gì?',
        options: ['A. Chèo thuyền', 'B. Câu cá', 'C. Đạp xe', 'D. Nhảy dây'],
        correctIndex: 1,
        explanation: 'Đó là hành động ĐI CÂU CÁ (phao nhấp nháy, người giật cần).',
        timeLimit: 12,
      },
      {
        id: 't5',
        question: 'Bác Hồ sinh ngày tháng năm nào?',
        options: ['A. 19/05/1890', 'B. 02/09/1945', 'C. 30/04/1975', 'D. 20/11/1982'],
        correctIndex: 0,
        explanation: 'Chủ tịch Hồ Chí Minh sinh ngày 19 tháng 5 năm 1890 tại Kim Liên, Nam Đàn, Nghệ An.',
        timeLimit: 12,
      },
    ],
  },
];
